# 1. 리스트,딕셔너리 & for loop

① 1~100 까지의 숫자 중 홀수이면서 3의 배수를 리스트로 저장하시오. (for loop를 사용하시오)

In [5]:
# 방법1
list1 = []
for i in range(1, 101) :
    if (i % 2 == 1) & (i % 3 == 0) :
        list1.append(i)
print(list1)

[3, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99]


In [10]:
# 방법2
list1 = [i for i in range(1, 101) if (i % 2 == 1) & (i % 3 == 0)]
print(list1)

[3, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99]


In [13]:
# 방법3
list1 = list(range(3, 101, 6))
print(list1)

[3, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99]


② 숫자를 반복적으로 입력 받아 계속 더해 갑니다. 더한 숫자가 30을 넘으면 반복문을 멈추고 총 합계를 출력합니다.

In [17]:
# while 문
tot = 0
while (True) :
    numbers = int(input())
    tot += numbers
    if tot > 30 :
        print(tot)
        break

23
21
44


In [22]:
# for 문
tot = 0
for _ in range(2) :
    n = int(input())
    tot += n
print(tot)

23
21
44


③ 아래 정의로 딕셔너리를 생성하시오.  
 d1 = { 'v1':23, 'v2':[1,3,5,7,9], 'v3':{'a':23, 'b':45}} 
 
생성한 딕셔너리로 부터 다음을 출력하시오.  
- v2의 값 전체  
- v2의 값 7  
- v3의 값 23  

In [23]:
d1 = {'v1':23, 'v2':[1, 3, 5, 7, 9], 'v3':{'a':23, 'b':45}}

print(d1['v2'])
print(d1['v2'][3])
print(d1['v3']['a'])

[1, 3, 5, 7, 9]
7
23


----------------------------------------------------------------------

# 2.numpy

★ numpy  
- numpy에서 axis=0 는 열
- numpy에서 axis=1 는 행

★ pandas  
- pandas에서 axis=0 는 행  
- pandas에서 axis=1 는 열

① 리스트를 이용하여 2차원 배열을 생성하고,  
 list1 = [[1,2,3,4,5],[4,5,6,7,8]]  
 
다음을 수행하시오.

In [51]:
import numpy as np
list1 = [[1, 2, 3, 4, 5], [4, 5, 6, 7, 8]] # 2차원 리스트 만들기

# array → np.array
a = np.array(list1) # 리스트를 numpy array로 바꿔서 a에 넣기

- shape  

In [47]:
print(a.shape)

(2, 5)


- 합, 평균, 표준편차  
    - 전체  
    - 열 기준 (# numpy에서 axis = 0)  
    - 행 기준 (# numpy에서 axis = 1)  

방법1 - numpy로 구하기

In [67]:
print('list1으로 만든 배열a:')
print(a)

# 합
print('[합]', '=' * 50)
print('전체 합:', np.sum(a)) # 합 - 전체
print('열 기준 합:', np.sum(a, axis=0)) # pandas에서 axis=0 는 행
print('행 기준 합:', np.sum(a, axis=1)) # pandas에서 axis=1 는 열

# 평균
print('[평균]', '=' * 50)
print('전체 평균:', np.mean(a))
print('열 기준 평균:', np.mean(a, axis=0))
print('행 기준 평균:', np.mean(a, axis=1))

# 표준편차
print('[표준편차]', '=' * 50)
print('전체 표준편차:', np.std(a))
print('열 기준 평균:', np.std(a, axis=0))
print('행 기준 평균:', np.std(a, axis=1))

list1으로 만든 배열a:
[[1 2 3 4 5]
 [4 5 6 7 8]]
[합] ==================================================
전체 합: 45
열 기준 합: [ 5  7  9 11 13]
행 기준 합: [15 30]
[평균] ==================================================
전체 평균: 4.5
열 기준 평균: [2.5 3.5 4.5 5.5 6.5]
행 기준 평균: [3. 6.]
[표준편차] ==================================================
전체 표준편차: 2.0615528128088303
열 기준 평균: [1.5 1.5 1.5 1.5 1.5]
행 기준 평균: [1.41421356 1.41421356]


방법2 - array로 구하기

In [76]:
print('list1으로 만든 배열a:')
print(a)

# 합
print('[합]', '=' * 50)
print('전체 합:', a.sum()) # 합 - 전체
print('열 기준 합:', a.sum(axis=0)) 
print('행 기준 합:', a.sum(axis=1)) 

# 평균
print('[평균]', '=' * 50)
print('전체 평균:', a.mean())
print('열 기준 평균:', a.mean(axis=0))
print('행 기준 평균:', a.mean(axis=1))

# 표준편차
print('[표준편차]', '=' * 50)
print('전체 표준편차:', a.std())
print('열 기준 평균:', a.std(axis=0))
print('행 기준 평균:', a.std(axis=1))

list1으로 만든 배열a:
[[1 2 3 4 5]
 [4 5 6 7 8]]
[합] ==================================================
전체 합: 45
열 기준 합: [ 5  7  9 11 13]
행 기준 합: [15 30]
[평균] ==================================================
전체 평균: 4.5
열 기준 평균: [2.5 3.5 4.5 5.5 6.5]
행 기준 평균: [3. 6.]
[표준편차] ==================================================
전체 표준편차: 2.0615528128088303
열 기준 평균: [1.5 1.5 1.5 1.5 1.5]
행 기준 평균: [1.41421356 1.41421356]


② np.where( 조건, True일때, False일때) 

np.where를 이용하여 값이 짝수이면 1, 아니면 0을 출력하시오.  
https://numpy.org/doc/stable/reference/generated/numpy.where.html  
(https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [79]:
# 2) np.where(조건, 참일때 값, 거짓일때 값)
print(a)

print(np.where(a % 2 == 0, 1, 0))

[[1 2 3 4 5]
 [4 5 6 7 8]]
[[0 1 0 1 0]
 [1 0 1 0 1]]


③ np.argmax, np.argmin  
- np.argmax : 가장 큰 값의 인덱스를 반환  
https://numpy.org/doc/stable/reference/generated/numpy.argmax.html  

- np.argmin : 가장 작은 값의 인덱스를 반환
https://numpy.org/doc/stable/reference/generated/numpy.argmin.html  

- 어레이 a에 대해서  
   - 전체에서  
   - 열 기준 (axis = 0)  
   - 행 기준 (axis = 1)  

In [90]:
import numpy as np
list1 = [[11,23,38],[25,31,19]]
a = np.array(list1)
print(a)

[[11 23 38]
 [25 31 19]]


In [91]:
# np.argmax : 가장 큰 값의 인덱스를 반환
print('전체에서 가장 큰 값의 인덱스:', np.argmax(a)) # 전체에서 2번째 인덱스 값: 38
print('열 기준 가장 큰 값의 인덱스:', np.argmax(a, axis=0)) # 열 기준 인덱스 값: 25, 31, 28
print('행 기준 가장 큰 값의 인덱스:', np.argmax(a, axis=1)) # 행 기준 인덱스 값: 38, 31

전체에서 가장 큰 값의 인덱스: 2
열 기준 가장 큰 값의 인덱스: [1 1 0]
행 기준 가장 큰 값의 인덱스: [2 1]


In [97]:
# np.argmin : 가장 작은 값의 인덱스를 반환
print('전체에서 가장 작은 값의 인덱스:', np.argmin(a)) # 전체에서 0번째 인덱스 값: 11
print('열 기준 가장 작은 값의 인덱스:', np.argmin(a, axis=0)) # 열 기준 인덱스 값: 11, 23, 19
print('행 기준 가장 작은 값의 인덱스:', np.argmin(a, axis=1)) # 행 기준 인덱스 값: 11, 19

전체에서 가장 작은 값의 인덱스: 0
열 기준 가장 작은 값의 인덱스: [0 0 1]
행 기준 가장 작은 값의 인덱스: [0 2]


----------------------------------------------------------------------

# 3. Pandas1

① 데이터프레임에 대해서, 불러와서 상위 10개 행을 조회하세요.  
path = "https://bit.ly/3FsgwkJ"

In [102]:
import pandas as pd
path = 'https://bit.ly/3FsgwkJ' # 타이타닉
titanic = pd.read_csv(path)

print(titanic.head(10))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54

② 데이터프레임의 Age만 조회하시오.

In [103]:
print(titanic['Age'])

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64


③ 데이터프레임에서 1~5행까지, Name, Age, Embarked 를 조회

In [107]:
print(titanic.loc[ 1:5, ['Name', 'Age', 'Embarked']])

                                                Name   Age Embarked
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0        C
2                             Heikkinen, Miss. Laina  26.0        S
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0        S
4                           Allen, Mr. William Henry  35.0        S
5                                   Moran, Mr. James   NaN        Q


④ Age가 70세 이상인 탑승객을 조회하시오.

In [121]:
# 방법1
print(titanic.loc[titanic['Age'] >= 70, :])

     PassengerId  Survived  Pclass                                  Name  \
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2           Mitchell, Mr. Henry Michael   
745          746         0       1          Crosby, Capt. Edward Gifford   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
96   male  71.0      0      0    PC 17754  34.6542    A5        C  
116  male  70.5      0      0      370369   7.7500   NaN        Q  
493  male  71.0      0      0    PC 17609  49.5042   NaN        C  
630  male  80.0      0      0       27042  30.0000   A23        S  
672  male  70.0      0      0  C.A. 24580  10.5000 

In [122]:
# 방법2
print(titanic.loc[titanic['Age'] >= 70])

     PassengerId  Survived  Pclass                                  Name  \
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2           Mitchell, Mr. Henry Michael   
745          746         0       1          Crosby, Capt. Edward Gifford   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
96   male  71.0      0      0    PC 17754  34.6542    A5        C  
116  male  70.5      0      0      370369   7.7500   NaN        Q  
493  male  71.0      0      0    PC 17609  49.5042   NaN        C  
630  male  80.0      0      0       27042  30.0000   A23        S  
672  male  70.0      0      0  C.A. 24580  10.5000 

In [125]:
# 방법3
print(titanic[titanic['Age'] >= 70])

     PassengerId  Survived  Pclass                                  Name  \
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2           Mitchell, Mr. Henry Michael   
745          746         0       1          Crosby, Capt. Edward Gifford   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
96   male  71.0      0      0    PC 17754  34.6542    A5        C  
116  male  70.5      0      0      370369   7.7500   NaN        Q  
493  male  71.0      0      0    PC 17609  49.5042   NaN        C  
630  male  80.0      0      0       27042  30.0000   A23        S  
672  male  70.0      0      0  C.A. 24580  10.5000 

⑤ Age가 60세 이상이고, 성별이 여성인 탑승객을 조회하시오.

In [141]:
print(titanic.loc[(titanic['Age'] >= 60) & (titanic['Sex'] == 'female')])

     PassengerId  Survived  Pclass  \
275          276         1       1   
366          367         1       1   
483          484         1       3   
829          830         1       1   

                                                 Name     Sex   Age  SibSp  \
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  female  60.0      1   
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   

     Parch  Ticket     Fare Cabin Embarked  
275      0   13502  77.9583    D7        S  
366      0  110813  75.2500   D37        C  
483      0    4134   9.5875   NaN        S  
829      0  113572  80.0000   B28      NaN  


⑥ Age가 20~22 사이인 탑승객을 조회하시오.

In [142]:
# 방법1
print(titanic.loc[(titanic['Age'] >= 20) & (titanic['Age'] <= 22)])

     PassengerId  Survived  Pclass                            Name     Sex  \
0              1         0       3         Braund, Mr. Owen Harris    male   
12            13         0       3  Saundercock, Mr. William Henry    male   
37            38         0       3        Cann, Mr. Ernest Charles    male   
51            52         0       3    Nosworthy, Mr. Richard Cater    male   
56            57         1       2               Rugg, Miss. Emily  female   
..           ...       ...     ...                             ...     ...   
836          837         0       3                Pasic, Mr. Jakob    male   
840          841         0       3     Alhomaki, Mr. Ilmari Rudolf    male   
861          862         0       2     Giles, Mr. Frederick Edward    male   
876          877         0       3   Gustafsson, Mr. Alfred Ossian    male   
882          883         0       3    Dahlberg, Miss. Gerda Ulrika  female   

      Age  SibSp  Parch            Ticket     Fare Cabin Embark

In [146]:
# 방법2 - between(이상, 이하)
print(titanic[titanic['Age'].between(20, 22)])

     PassengerId  Survived  Pclass                            Name     Sex  \
0              1         0       3         Braund, Mr. Owen Harris    male   
12            13         0       3  Saundercock, Mr. William Henry    male   
37            38         0       3        Cann, Mr. Ernest Charles    male   
51            52         0       3    Nosworthy, Mr. Richard Cater    male   
56            57         1       2               Rugg, Miss. Emily  female   
..           ...       ...     ...                             ...     ...   
836          837         0       3                Pasic, Mr. Jakob    male   
840          841         0       3     Alhomaki, Mr. Ilmari Rudolf    male   
861          862         0       2     Giles, Mr. Frederick Edward    male   
876          877         0       3   Gustafsson, Mr. Alfred Ossian    male   
882          883         0       3    Dahlberg, Miss. Gerda Ulrika  female   

      Age  SibSp  Parch            Ticket     Fare Cabin Embark

isin() 메서드 : 데이터가 있는지 판별해준다.  
- Series.isin(values)  
- DataFrame.isin(values)

In [148]:
# isin() 에서 리스트로 조회
print(titanic[titanic['Age'].isin([20, 21, 22])]) # 20세 or 21세 or 22세 ← 이렇게 조회한거랑 똑같은 의미!`ㄴ

     PassengerId  Survived  Pclass                            Name     Sex  \
0              1         0       3         Braund, Mr. Owen Harris    male   
12            13         0       3  Saundercock, Mr. William Henry    male   
37            38         0       3        Cann, Mr. Ernest Charles    male   
51            52         0       3    Nosworthy, Mr. Richard Cater    male   
56            57         1       2               Rugg, Miss. Emily  female   
..           ...       ...     ...                             ...     ...   
836          837         0       3                Pasic, Mr. Jakob    male   
840          841         0       3     Alhomaki, Mr. Ilmari Rudolf    male   
861          862         0       2     Giles, Mr. Frederick Edward    male   
876          877         0       3   Gustafsson, Mr. Alfred Ossian    male   
882          883         0       3    Dahlberg, Miss. Gerda Ulrika  female   

      Age  SibSp  Parch            Ticket     Fare Cabin Embark

→ Age가 20세 이상 ~ 22세 이하를 찾고싶어서 isin() 메서드로 찾으니까  
→ 67개의 행이 나와야하는데 66개 행이 나오는 오류가 발생했다.  
→ 범위를 구할 때는 between() 메서드를 이용하자  
→ 특정값 조회는 isin() 메서드를 사용하자

⑦ Pclass가 1이거나 3인 탑승객을 조회하시오.

In [158]:
# 방법1
print(titanic.loc[(titanic['Pclass'] == 1) | (titanic['Pclass'] == 3)])

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [157]:
# 방법2
print(titanic.loc[titanic['Pclass'].isin([1,3]) ]) # 리스트로 조회

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

⑧ 승선지역(Embarked)별 평균 운임을 조회하시오.

In [161]:
print(titanic.groupby(by='Embarked', as_index=False)['Fare'].mean())

  Embarked       Fare
0        C  59.954144
1        Q  13.276030
2        S  27.079812


----------------------------------------------------------------------

# 4. Pandas2

① df1을 구성하는 data1, df2를 구성하는 data2가 아래와 같을 때, 두 데이터 프레임을 생성하고 행을 기준으로 병합하시오.  
data1 = {'col1': [1, 2], 'col2': ['a', 'b']}  
data2 = {'col1': [3, 4], 'col2': ['c', 'd']}

In [195]:
import pandas as pd

# 딕셔너리 data1의 키는 - 컬럼명
#                       - 리스트의 값들은 각각의 행에 대응하는 데이터
data1 = {'col1':[1, 2], 'col2':['a', 'b']}
#  df1 데이터프레임 생성
df1 = pd.DataFrame(data1, columns=['col1', 'col2'])
print(df1)

# 딕셔너리 data2의 키는 컬럼명
#                       리스트의 값들은 각각의 행에 대응하는 데이터
data2 = {'col1':[3, 4], 'col2':['c', 'd']}
#  df2 데이터프레임 생성
df2 = pd.DataFrame(data2, columns=['col1', 'col2'])
print(df2)

   col1 col2
0     1    a
1     2    b
   col1 col2
0     3    c
1     4    d


pd.concat( [데이터프레임1, 데이터프레임2] , axis=0) : **행**을 기준으로 병합  
axis=0가 디폴트 값

In [193]:
## 두 데이터 프레임을 생성하고 행을 기준으로 병합 ##
df = pd.concat([df1, df2], axis=0)
df

col1 col2
0     1    a
1     2    b
0     3    c
1     4    d

② 앞서 생성한 데이터 프레임 df1, df2를 열을 기준으로 병합하시오.  
data1 = {'col1': [1, 2], 'col2': ['a', 'b']}  
data2 = {'col1': [3, 4], 'col2': ['c', 'd']}

pd.concat( [데이터프레임1, 데이터프레임2] , axis=1) : **열**을 기준으로 병합  
axis=0가 디폴트 값

In [196]:
df = pd.concat([df1, df2], axis=1)
df

col1 col2  col1 col2
0     1    a     3    c
1     2    b     4    d